module.exports = [
  {
    id: 1,
    name: "Introduction",
    sections: 2,
    available: true,
    completed: false,
    images: "/images/introbag.png",
  },
  {
    id: 2,
    name: "Distress Tolerance",
    sections: 2,
    available: true,
    completed: false,
    images: "/images/tal1.png",
  },
  {
    id: 3,
    name: "Mindfulness",
    sections: 2,
    available: false,
    completed: false,
    images: "/images/mana1.png",
  },
  {
    id: 4,
    name: "Emotional Regulation",
    sections: 2,
    available: false,
    completed: false,
    images: "/images/edo1.png",
  },
  {
    id: 5,
    name: "Interpersonal Effectiveness",
    sections: 2,
    available: false,
    completed: false,
    images: "/images/igoRok1.png",
  },
  {
    id: 6,
    name: "Conclusion",
    sections: 2,
    available: false,
    completed: false,
    images: "/images/allfour.png",
  },
];
