module.exports = [
  {
    id: 1,
    name: "Welcome!",
    images: "introbag",
    title: "Introduction I",
    available: true,
    section_id: 1,
  },
  {
    id: 2,
    name: "Get Started",
    images: "introbag",
    title: "Introduction II",
    available: false,
    section_id: 2,
  },
  {
    id: 3,
    name: "Basic DT I",
    images: "tal1",
    title: "Basic DT",
    available: false,
    section_id: 3,
  },
  {
    id: 4,
    name: "Basic DT II",
    images: "tal1",
    title: "Basic DT",
    available: false,
    section_id: 3,
  },
  {
    id: 5,
    name: "Basic DT III",
    images: "tal1",
    title: "Basic DT",
    available: false,
    section_id: 3,
  },
  {
    id: 6,
    name: "Basic DT IV",
    images: "tal1",
    title: "Basic DT",
    available: false,
    section_id: 3,
  },
  {
    id: 7,
    name: "Advanced DT I",
    images: "tal2",
    title: "Advanced DT",

    available: false,
    section_id: 4,
  },
  {
    id: 8,
    name: "Advanced DT II",
    images: "tal2",
    title: "Advanced DT",

    available: false,
    section_id: 4,
  },
  {
    id: 9,
    name: "Advanced DT III",
    images: "tal2",
    title: "Advanced DT",

    available: false,
    section_id: 4,
  },
  {
    id: 10,
    name: "Advanced DT IV",
    images: "tal2",
    title: "Advanced DT",

    available: false,
    section_id: 4,
  },
  {
    id: 11,
    name: "Basic Mindfulness I",
    images: "tal2",
    title: "Basic Mindfulness",
    available: false,
    section_id: 5,
  },
  {
    id: 12,
    name: "Basic Mindfulness II",
    images: "tal2",
    title: "Basic Mindfulness",
    available: false,
    section_id: 5,
  },
];
